apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::884595506241:role/eksctl-capstone-nodegroup-ng-976b-NodeInstanceRole-140GSJ19Q4EII
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::884595506241:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-06T09:45:21Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1577"
  uid: 3e1b36c4-56f3-4fce-91f6-44a27ce0a19d
